name: Deploy EriduBot to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - name: Checkout del Repositorio
        uses: actions/checkout@v4

      - name: Instalar Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Desplegar en Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
